### PR TITLE
fix filterByDistanceFrom(..)

### PR DESCRIPTION
**Pull request by mpoiriert**
The missing variable from the template have been fixe.

### CODE REVIEW

**Comment by willdurand** [comment]
I don't get your patch..

**Comment by mpoiriert** [comment]
It's concerning the pull request 29

In MySQL you can't use WHERE with a generated column, so using filterByDistanceFrom with the new 'Distance'-column crashes:
"Unable to execute SELECT statement 
[SELECT *, ABS(6371 \* ACOS(x \* COS(RADIANS(lat)) \* COS(RADIANS(lng) - y) + z \* SIN(RADIANS(lat)))) AS Distance FROM table WHERE Distance < :p1] 
[wrapped: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Distance' in 'where clause']"

Even the HAVING-clause, which works with newer MySQL versions could be used in this context, does not work with older versions.
So due to compatibility issues I think this file should be reverted (even if that means duplicated code...)

I just properly fix it starting from the change of dominik (his pull request wasn't passing travis).

**Comment by mpoiriert** [comment]
If there is any reason why you can't accept the pull request let me know I might have time to adjust it. I starting to use this behavior in a symfony2 project and I prefer to use the main repo than overriding it with a fork...

**Comment by snoopckuu** [comment]
@willdurand i have the same problem. Could you please merge this?

**Comment by willdurand** [comment]
Merged, thanks!

**Pull request closed without merging**
