### PR TITLE
withDistance query method

### PR DESCRIPTION
**Pull request by smhg**
See #27.

Please let me know if this is ok for you.
If so, I will send a separate PR with a Readme update.

### CODE REVIEW

**Comment by willdurand** [comment]
Yep. Looks good to me. Could you please:
1. add the README to this PR,
2. squash your commits?

Thanks!

**Comment by smhg** [comment]
Readme added and squashed. Thank you!

**Comment by willdurand** [comment]
Thanks <3

**Comment by willdurand** [comment]
Just tagged `1.2.0`.

**Pull request merged**
